# This is a basic workflow to help you get started with Actions
name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the eleven branch
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo 'Asia/Shanghai' > /etc/timezone
          apt-get update -qq && apt-get upgrade -y && apt-get install --no-install-recommends -y ca-certificates curl git tar unzip wget zip zstd
          chmod a+x build/build_kernel.sh
          bash build/build_kernel.sh
